<script>
  const emailAddress = 'hey@alextorres.me';
  const mailto = `mailto:${emailAddress}?subject=Project inquiry`;
</script>

<style>
  .description {
    max-width: 800px;
    margin: 0 30px 50px 30px;
  }

  .cta {
    background-color: rgb(240, 237, 220);
    padding: 30px;
    max-width: 740px;
    margin: 50px 30px;
  }

  .map-embed {
    display: block;
    width: calc(100% - 60px);
    margin: 0 30px;
    height: 70vh;
    min-height: 500px;
    border: 1px solid rgb(240, 237, 220);
  }

  .poster {
    width: 100%;
    border: 1px solid rgb(240, 237, 220);
  }
</style>

<svelte:head>
  <title>EMT - network map and printed infographics - Alex Torres</title>
  <meta
    name="description"
    content="An embeddable network map library and a browser-based PDF system that prints the infographics at real bus stops." />
  <meta property="og:type" content="website" />
  <meta property="og:title" content="EMT - network map and printed infographics - Alex Torres" />
  <meta property="og:description" content="An embeddable network map library and a browser-based PDF system that prints the infographics at real bus stops." />
  <meta property="og:image" content="https://alextorres.me/og/emt.png" />
  <meta name="twitter:card" content="summary_large_image" />
</svelte:head>

<div class="description">
  <p><a href="/services">← services</a> · <a href="/servicios/emt">español</a></p>

  <h1>EMT — network map and printed infographics</h1>

  <h2>The problem</h2>
  <p>
    A public bus operator needs its network to be understandable in two very
    different places: on the web, where riders explore lines and stops
    interactively, and on the street, where every stop and pole carries
    printed infographics that must stay in sync with the actual network.
  </p>

  <h2>What I built</h2>
  <p>
    Two connected systems sharing the same network data:
  </p>
  <ul>
    <li>
      <b>An embeddable map library</b> — a JavaScript library (single-file
      bundle, plain JS API) that any of the operator's sites can drop in to
      render the interactive map of lines and stops.
    </li>
    <li>
      <b>An infographics engine</b> — the browser as a layout engine: a
      slot-based design system composes the infographic for each stop and
      pole, and an API renders it to print-ready PDF. When the network
      changes, the printed material regenerates instead of being redrawn by
      hand.
    </li>
  </ul>

  <h2>The result</h2>
  <p>
    The infographics generated by this system are printed and installed at
    real bus stops, and the same source of truth powers the interactive map —
    web and street never disagree.
  </p>
  <p>
    A real example, generated by the system for a bus shelter —
    <a href="/emt-marquesina.pdf" rel="noopener">open the full PDF</a>:
  </p>
  <a href="/emt-marquesina.pdf" rel="noopener">
    <img
      class="poster"
      src="/emt-marquesina.png"
      alt="Bus-shelter infographic for stop 2417: line thermometers for lines 4, 19, 20 and N3, fares and legend" />
  </a>

  <h2>Try it</h2>
  <p>
    The schematic network map, live — or
    <a href="https://bus-map.alextorres.me" rel="noopener">open it full screen</a>.
    Map graphic design by
    <a href="https://geotoni.eu" rel="noopener">Toni</a>.
  </p>
</div>

<iframe
  class="map-embed"
  src="https://bus-map.alextorres.me"
  title="EMT interactive network map"
  loading="lazy"></iframe>

<div class="description">
  <p>
    The same approach powers the network map of
    <a href="https://castello-map.alextorres.me" rel="noopener">Castelló</a>.
  </p>
</div>

<div class="cta">
  <p>
    Need your network data turned into maps or print?
    Write me at <a href={mailto}>{emailAddress}</a>.
  </p>
</div>
